// ignore_for_file: constant_identifier_names, non_constant_identifier_names

import 'package:flutter/material.dart';

//! Base
const WHITE_COLOR = Color(0xFFFFFFFF);
const BLACK_COLOR = Color(0xFF000000);
const MEDIUM_ORCHID_COLOR = Color(0xffaa45e3);
const COSMIC_COBALT = Color(0xff3B3486);
const UNITED_NATIONS_BLUE_COLOR = Color(0xff5982e8);
const PASTEL_BLUE_COLOR = Color(0xffA1CCD1);
const BURLYWOOD_COLOR = Color(0xffE9B384);
const CULTURED_COLOR = Color(0xFFf7f7f7);
const BRIGHT_GRAY_COLOR = Color(0xFFEEEEEE);
const DIM_GRAY_COLOR = Color(0xFF686868);
const BLACK_COFFEE_COLOR = Color(0xFF332d2d);
const AWESOME_COLOR = Color(0xFFFF1744);
const GO_GREEN_COLOR = Color(0xFF00b761);
const PLATINUM_COLOR = Color(0xFFE6E6E6);
const SPIRO_DISCO_BALL_COLOR = Color(0xff2ccaf1);
const ORANGE_RED_COLOR = Color(0xFFFF5252);
// const SPANISH_GRAY = Color(0xFF9E9E9E);
const CHINESE_WHITE = Color(0xFFE0E0E0);
const EGGSHELL = Color(0xffF0EDCF);
const PAOLOVERONESEGREEN = Color(0xff0D9276);
const RAJAH = Color(0xffFFBB64);
const TEAGREEN = Color(0xffD5F0C1);

//! رنگهای تایید شده
const APPLE = Color(0xff80c342);
const BRIGHTYELLOW = Color(0xfffaa61a);

const CORNSILK = Color(0xffFFF8E1);
const INDEPENDENCE = Color(0xff464667);
const YANKEES_BLUE = Color(0xff0B2C3D);
const RAISIN_BLACK = Color(0xff222222);
const GREEN_RYB = Color(0xff6DB12E);
const BRIGHT_GRAY = Color(0xffE6EAF4);
const CHINESE_SILVER = Color(0xffCDCDCD);
const NYANZA = Color(0xffEDFFDC);
const BUBBLES = Color(0xffE4F4FF);
const CULTURED_1 = Color(0xffF4F4F4);
const BLUE_COLA = Color(0xff007ED9);
const DODGER_BLUE = Color(0xff169DFF);
const BROWN_NOSE = Color(0xff733D24);
const LIGHT_TAUPE = Color(0xffBF8970);
const LIGHT_GOLD = Color(0xffB1970A);
const GOLD_WEB_GOLDEN = Color(0xffFFD700);
const BRIGHT_YELLOW_CRAYOLA = Color(0xffFAA61A);
const GRANITE_GRAY = Color(0xff666666);
const CULTURED = Color(0xffF7F6F3);
const GRAY_X11 = Color(0xffBBBBBB);
const ANTI_FLASH_WHITE = Color(0xffF3F3F3);
const CHINESE_SILVER1 = Color(0xffCDCDCD);
const CHINESE_SILVER2 = Color(0xffCBCBCB);
const GHOST_WHITE = Color(0xffF9FAFB);
const LIGHT_SILVER = Color(0xffD9D9D9);
const LAVENDER_WEB = Color(0xffE1EAFE);
const ALICE_BLUE = Color(0xffF4F7FE);
const LAVENDER_BLUSH = Color(0xffFFF2F2);
const OLD_SILVER = Color(0xff868686);
const BOSTON_UNIVERSITY_RED = Color(0xffC30000);
const WHITE = Color(0xffFFFFFF);
const SPANISH_GRAY = Color(0xff999999);
const BLACK_OLIVE = Color(0xff404040);
const JET = Color(0xff353535);
const HELIOTROPE = Color(0xffC875FB);
const CADMIUM_BLUE = Color(0xff100493);
const CANARY_YELLOW = Color(0xffFFEE00);
const AIR_FORCE_BLUE = Color(0xff00308B);

//! Main
// const COLOR_PRIMARY = MEDIUM_ORCHID_COLOR;
// const COLOR_SECONDARY = UNITED_NATIONS_BLUE_COLOR;
const COLOR_PRIMARY = APPLE;
const COLOR_SECONDARY = BLACK_COLOR;

//! Background
const BACKGROUND_LIGHT_COLOR = WHITE_COLOR;
const BACKGROUND_DARK_COLOR = BLACK_COLOR;
const BACKGROUND_GRAY_COLOR = DIM_GRAY_COLOR;
const BACKGROUND_STAR_COLOR = GOLD_WEB_GOLDEN;
const BACKGROUND_AWARD_COLOR = GOLD_WEB_GOLDEN;
const BACKGROUND_NEW_PROMOTION_COLOR = BRIGHT_GRAY;
const BACKGROUND_PAGE_COLOR = CULTURED_1;

//! AppBar
const APPBAR_BACKGROUND_LIGHT_COLOR = WHITE;
const APPBAR_BACKGROUND_DARK_COLOR = COLOR_SECONDARY;

//! StatusBAr
const APPBAR_STATUS_BAR_LIGHT_COLOR = COLOR_PRIMARY;
const APPBAR_STATUS_BAR_DARK_COLOR = COLOR_SECONDARY;
const APPBAR_STATUS_BAR_GRAY_COLOR = SPANISH_GRAY;

//! Text
const TEXT_MESSAGE_SUCCESS_COLOR = COLOR_PRIMARY;
const TEXT_MESSAGE_ERROR_COLOR = BOSTON_UNIVERSITY_RED;
const TEXT_MESSAGE_INFO_COLOR = DODGER_BLUE;
const TEXT_MESSAGE_WARNING_COLOR = LIGHT_TAUPE;
const TEXT_POPUP_BUTTON_CANCEL_COLOR = BOSTON_UNIVERSITY_RED;
const TEXT_POPUP_BUTTON_CONFIRM_COLOR = INDEPENDENCE;
const TEXT_POPUP_CONTENT_COLOR = BLACK_OLIVE;
const TEXT_ANSWER_COLOR = GRANITE_GRAY;
const TEXT_DATE_COLOR = OLD_SILVER;

const TEXT_LIGHT_COLOR = WHITE_COLOR;
const TEXT_DARK_COLOR = BLACK_COLOR;
const TEXT_GRAY_COLOR = DIM_GRAY_COLOR;
const TEXT_GRAY_ONE_COLOR = GRAY_X11;
final TEXT_HINT_GRAY_COLOR = DIM_GRAY_COLOR.withAlpha(150);
const TEXT_LINK_COLOR = SPIRO_DISCO_BALL_COLOR;
const TEXT_PRIMARY_COLOR = COLOR_PRIMARY;
const TEXT_SECONDARY_COLOR = COLOR_SECONDARY;
const TEXT_REMAINING_TIME_COLOR = CANARY_YELLOW;

//! Button
const BUTTON_BACKGROUND_COLOR = COLOR_PRIMARY;
const BUTTON_TEXT_COLOR = CULTURED;
const BUTTON_DISABLED_TEXT_COLOR = INDEPENDENCE;
const BUTTON_BACKGROUND_DISABLED_COLOR = ALICE_BLUE;
const BUTTON_BACKGROUND_DANGER_COLOR = ORANGE_RED_COLOR;
const BUTTON_BACKGROUND_CANCEL_COLOR = LAVENDER_BLUSH;
const BUTTON_BACKGROUND_CONFIRM_COLOR = ALICE_BLUE;
const BUTTON_BACKGROUND_CLOSE_COLOR = JET;
const BUTTON_BACKGROUND_BACK_COLOR = GRAY_X11;
const BUTTON_BACKGROUND_EXIT_COLOR = BOSTON_UNIVERSITY_RED;

//! Switch
const SWITCH_CHECKED_THUMB_COLOR = COLOR_SECONDARY;
final SWITCH_NOT_CHECKED_THUMB_COLOR = DIM_GRAY_COLOR.withAlpha(210);
final SWITCH_CHECKED_TRACK_COLOR = COLOR_SECONDARY.withAlpha(140);
final SWITCH_NOT_CHECKED_TRACK_COLOR = DIM_GRAY_COLOR.withAlpha(60);

//! TextField
const TEXT_FIELD_TEXT_COLOR = RAISIN_BLACK;
const TEXT_FIELD_HINT_COLOR = SPANISH_GRAY;
const TEXT_FIELD_ICON_COLOR = CHINESE_SILVER1;
const TEXT_FIELD_SEARCH_COLOR = GHOST_WHITE;

const TEXT_FIELD_BACKGROUND_LIGHT_COLOR = BRIGHT_GRAY_COLOR;
const TEXT_FIELD_BACKGROUND_DARK_COLOR = DIM_GRAY_COLOR;
const TEXT_FIELD_BORDER_LIGHT_COLOR = DODGER_BLUE;
const TEXT_FIELD_BORDER_DARK_COLOR = COLOR_PRIMARY;
const TEXT_FIELD_ENABLED_BORDER_LIGHT_COLOR = BRIGHT_GRAY_COLOR;
const TEXT_FIELD_ENABLED_BORDER_DARK_COLOR = BRIGHT_GRAY_COLOR;
const TEXT_FIELD_INACTIVE_COLOR = DIM_GRAY_COLOR;

//! Container
const CONTAINER_ERROR_COLOR = ORANGE_RED_COLOR;
const CONTAINER_GRAY_COLOR = SPANISH_GRAY;
const CONTAINER_GRAYLIGHT = CHINESE_WHITE;
const CONTAINER_CIRCEL = LIGHT_SILVER;

//! FloatingActionButton

const BACKGROUND_LIGHT_COLOR_FLOATING_BUTTON = COLOR_SECONDARY;
const BACKGROUND_DARK_COLOR_FLOATING_BUTTON = COLOR_SECONDARY;
const BACKGROUND_LIGHT_ICON_COLOR_FLOATING_BUTTON = BACKGROUND_LIGHT_COLOR;
const BACKGROUND_DARK_ICON_COLOR_FLOATING_BUTTON = BACKGROUND_LIGHT_COLOR;
const BACKGROUND_LIGHT_TEXT_COLOR_FLOATING_BUTTON = BACKGROUND_LIGHT_COLOR;
const BACKGROUND_DARK_TEXT_COLOR_FLOATING_BUTTON = BACKGROUND_LIGHT_COLOR;

//! Icon
const BACKGROUND_LIGHT_COLOR_ICON = WHITE_COLOR;
const BACKGROUND_GRAY_COLOR_ICON = DIM_GRAY_COLOR;
const BACKGROUND_DARK_COLOR_ICON = COLOR_SECONDARY;
const BACKGROUND_PRIMARY_COLOR_ICON = COLOR_PRIMARY;
const BACKGROUND_SECONDARY_COLOR_ICON = COLOR_SECONDARY;
const BACKGROUND_COLOR_TEXTFIELD_ICON = CHINESE_SILVER1;
const BACKGROUND_COLOR_DELETE_ICON = BOSTON_UNIVERSITY_RED;
const BACKGROUND_COLOR_IMAGE = BACKGROUND_COLOR_TEXTFIELD_ICON;

//! Border
const BORDER_COLOR = CHINESE_SILVER1;
const BORDER_OTP_COLOR = CHINESE_SILVER2;
const BORDER_POPUP_COLOR = CHINESE_SILVER2;
const BORDER_ERROR_COLOR = BOSTON_UNIVERSITY_RED;
const BORDER_SAVE_SCORES_COLOR = APPLE;
const BORDER_FULL_SCORES_COLOR = DODGER_BLUE;
const BORDER_BUTTOMM = AIR_FORCE_BLUE;

//! Message
const MESSAGE_SUCCESS_COLOR = NYANZA;
const MESSAGE_ERROR_COLOR = LAVENDER_BLUSH;
const MESSAGE_INFO_COLOR = BUBBLES;
const MESSAGE_WARNING_COLOR = CORNSILK;

//! category
const BACKGROUND_CATEGORY_DISABLE_COLOR = ANTI_FLASH_WHITE;
const BACKGROUND_CATEGORY_ENABLE_COLOR = DODGER_BLUE;

//! background lottery
const BACKGROUND_LOTTERY_COLOR_1 = HELIOTROPE;
const BACKGROUND_LOTTERY_COLOR_2 = CADMIUM_BLUE;
